### ISSUE TITLE
GitPod link not working

### ISSUE THREAD

**Issue by Nilllas** [vwxyzjn/cleanrl#103]
## Problem Description
Link to GitPod dev environment on instructions page not working. Dev environment not opening in GitPod. Error message saying that there is not GitPod file in repository.

## Current Behavior
See above.

## Expected Behavior
Dev environment opening in GitPod.

## Possible Solution
Fix GitPod link 

## Steps to Reproduce
Try to click on GitPod banner-link on instructions page.

**Comment by vwxyzjn** [comment]
Could you check if it is fixed?

**Comment by Nilllas** [comment]
Seems working fine now. Thanks!
