### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by mf093087** [vwxyzjn/cleanrl#111]
I try to install this package on windows. When I installed poetry, when I run poetry run ppo.py, I met the following errors:

[WinError 193] %1 is not a valid Win32 application

  at c:\users\username\onedrive\anaconda3\lib\subprocess.py:1311 in _execute_child
      1307│             sys.audit("subprocess.Popen", executable, args, cwd, env)
      1308│
      1309│             # Start the process
      1310│             try:
    → 1311│                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      1312│                                          # no special security
      1313│                                          None, None,
      1314│                                          int(not close_fds),
      1315│                                          creationflags,

**Comment by vwxyzjn** [comment]
Hey not sure why this happens but maybe try installing without anaconda.

**Comment by mf093087** [comment]
Yes I will try, thanks a lot

**Comment by vwxyzjn** [comment]
Cl
