### ISSUE TITLE
Re-think Open RL Benchmark.

### ISSUE THREAD

**Issue by vwxyzjn** [vwxyzjn/cleanrl#123]
I am thinking of re-doing the Open RL Benchmark that also includes benchmarks from other popular RL libraries, and CleanRL is just one of them. So we would have wandb and github projects like 

* openrlbenchmark/cleanrl
* openrlbenchmark/baselines
* openrlbenchmark/sb3
* openrlbenchmark/tianshou
* openrlbenchmark/rllib

And the good thing is that anyone can use the recorded metrics in the Open RL Benchmark like explained here: https://github.com/wandb/client/issues/3231; so the contribution is that no one has to re-run the baselines experiments if they just want to compare the results.

**Comment by yooceii** [comment]
SGTM

**Comment by vwxyzjn** [comment]
I put up a draft document here: https://docs.google.com/document/d/1cDI_AMr2QVmkC53dCHFMYwGJtLC8V4p6KdL2wnYPaiI/edit?usp=sharing

**Comment by vwxyzjn** [comment]
Closed in favor of https://github.com/openrlbenchmark/openrlbenchmark
