### ISSUE TITLE
Investigate ` nn.utils.clip_grad_norm_` for DQN, DDPG, and TD3

### ISSUE THREAD

**Issue by vwxyzjn** [vwxyzjn/cleanrl#148]
## Problem Description

Compared to the original implementations, our DQN, DDPG, and TD3 implementations additionally do global gradient clipping, a code-level optimization done in PPO. It is unclear if global gradient clipping offers real performance benefits, so we should look into it and remove it if necessary.

- [ ] `dqn_atari.py`
- [ ] `ddpg_continuous_action.py`
- [ ] `td3_continuous_action.py`

**Comment by dosssman** [comment]
-[ ] `sac_continuous_action.py`
Queued up some runs for comparison here:

https://wandb.ai/openrlbenchmark/openrlbenchmark/reports/-TMP-MuJoCo-CleanRL-s-SAC-Grad-norm-check--VmlldzoxNzk2OTQ1

**Comment by dosssman** [comment]
:hourglass: `ddpg_continuous_action.py` [WANDB Tracking](https://wandb.ai/openrlbenchmark/openrlbenchmark/reports/-TMP-MuJoCo-CleanRL-s-DDPG-Grad-norm-check--VmlldzoxODAyODYx)
:hourglass:  `td3_continuous_action.py` [WANDB Tracking](https://wandb.ai/openrlbenchmark/openrlbenchmark/reports/-TMP-MuJoCo-CleanRL-s-TD3-Grad-norm-Check--VmlldzoxODAyODE2)

**Comment by vwxyzjn** [comment]
See https://github.com/vwxyzjn/cleanrl/pull/173#issuecomment-1114455961
