### ISSUE TITLE
KeyError: "terminal_observation" in dqn.py

### ISSUE THREAD

**Issue by Jackory** [vwxyzjn/cleanrl#155]
## Problem Description
when I run cleanrl/dqn.py, an error occurred：
in line 174：
![image](https://user-images.githubusercontent.com/52418786/162555376-9f827af6-3bfc-4f54-8d8c-f2ab1c443037.png)

My package version is here:
torch==1.7.1
gym==0.18.3
stable_baselines3==1.10

**Comment by vwxyzjn** [comment]
Please use the latest gym. Our master pins gym==0.23.1. 

To avoid having this problem I also suggest using `poetry install`. See https://docs.cleanrl.dev/get-started/installation/

**Comment by LLL-YUE** [comment]
> Please use the latest gym. Our master pins gym==0.23.1.
> 
> To avoid having this problem I also suggest using `poetry install`. See https://docs.cleanrl.dev/get-started/installation/
> 
> Feel free to re-open this issue if you still have trouble.

I can not solve this issue through this approach. Have somebody solved this issue?

**Comment by pseudo-rnd-thoughts** [comment]
What gym or gymnasium version are you using?
