### ISSUE TITLE
GAE bug with PPO2

### ISSUE THREAD

**Issue by vwxyzjn** [vwxyzjn/cleanrl#16]
The following results using GAE is clearly incorrect. The last value of the advantages array is very off.
![image](https://user-images.githubusercontent.com/5555347/79401122-39b06d00-7f56-11ea-9aff-a5590df754fc.png)

The reason for the bug might be related to `episode_lengths = [-1]`, where the GAE based calculation will set the last value of the advantages array incorrectly. This requires better implementation and fix.

**Comment by vwxyzjn** [comment]
https://github.com/openai/spinningup/blob/038665d62d569055401d91856abb287263096178/spinup/algos/pytorch/ppo/ppo.py#L44-L64 offers better implementation and it matches closer to the GAE described in the paper. Namely,

![image](https://user-images.githubusercontent.com/5555347/79401379-e854ad80-7f56-11ea-9d77-95687ddeea37.png)

![image](https://user-images.githubusercontent.com/5555347/79401395-f4d90600-7f56-11ea-939d-072e35336226.png)

We will probably push for something similar to that.

**Comment by vwxyzjn** [comment]
Fixed via the latest commit, please close the issue after review (if there is no problem) @dosssman

**Comment by dosssman** [comment]
`discount_sum` sounds like a safe bet for now

**Comment by dosssman** [comment]
I don't think I can close the issue though
