### ISSUE TITLE
Please specify in readme.md that is for Python3.8-3.9. 3.8+ is misleading because 3.10 leads to problems

### ISSUE THREAD

**Issue by ElliotMunro200** [vwxyzjn/cleanrl#175]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by vwxyzjn** [comment]
Hey @ElliotMunro200  thanks for reporting. Would you have the bandwidth to submit a PR to fix this? If not no worries I can do it.

**Comment by ElliotMunro200** [comment]
I'm very new with Git and Github but I've forked the project and created a PR. Hope it works fine.

**Comment by vwxyzjn** [comment]
> @ElliotMunro200 can you tell what problems you had with python >= 3.10 ? i would like to analyze the issue

If I remember correctly, this is because some dependencies do not support 3.10..

**Comment by ElliotMunro200** [comment]
I can't remember what I faced at the time when I originally did this.
I just made a fresh conda env with Python 3.10 and tried to install cleanrl
with "pip install -r requirements/requirements.txt".
I got many errors like "Ignoring absl-py: markers 'python_full_version >=
"3.7.1" and python_version < "3.10"' don't match your environment".
Neither could I execute "poetry install" as I got the error "Current Python
version (3.10.0) is not allowed by the project (>=3.7.1,<3.10).
Please change python executable via the "env use" command."
Hope this helps.
Cheers,
Elliot.
