### ISSUE TITLE
Wrong direction in readme.md file

### ISSUE THREAD

**Issue by ElliotMunro200** [vwxyzjn/cleanrl#176]
## Problem Description

This command in the README.md in cleanrl/benchmark/ddpg/ is wrong: "# reproduce the MuJoCo experiments bash cleanrl/ddpg/mujoco.sh"

## Current Behavior

Can't find the expected files

## Possible Solution

Probably due to refactoring of the repository

## Steps to Reproduce

1.
2.
3.
4.

**Comment by vwxyzjn** [comment]
Thanks for the reported error. The specific file you are looking for is https://github.com/vwxyzjn/cleanrl/blob/master/benchmark/ddpg/mujoco.sh

We are addressing this in a better way in https://github.com/vwxyzjn/cleanrl/pull/173. Stay tuned :)

**Comment by vwxyzjn** [comment]
Closed by #173
