### ISSUE TITLE
SAC doesn't work

### ISSUE THREAD

**Issue by vadim0x60** [vwxyzjn/cleanrl#179]
## Problem Description

Soft Actor-Critic (`sac_continuous_action.py`) just doesn't work. I have tried different envs, it doesn't matter

## Current Behavior

```
python cleanrl/sac_continuous_action.py --env-id 'MountainCarContinuous-v0'
```

```
Traceback (most recent call last):
  File "/home/320012346/cleanrl/cleanrl/sac_continuous_action.py", line 188, in <module>
    actor = Actor(envs).to(device)
  File "/home/320012346/cleanrl/cleanrl/sac_continuous_action.py", line 120, in __init__
    self.action_scale = torch.FloatTensor((env.action_space.high - env.action_space.low) / 2.0)
AttributeError: 'Tuple' object has no attribute 'high'
```

## Expected Behavior

```
python cleanrl/sac_continuous_action.py --env-id 'MountainCarContinuous-v0'
```

```
global_step=1, episodic_return=-0.0020000000949949026
global_step=7, episodic_return=-0.0060000005178153515
global_step=8, episodic_return=-0.0010000000474974513
global_step=25, episodic_return=-0.017000000923871994
```

## Possible Solution

Not sure. I think `gym.vector.SyncVectorEnv` handles action spaces incorrectly. The docstring says it chooses the action space of the first of the subenvironments, but in reality it's not a `gym.space`, it's a tuple.

**Comment by vwxyzjn** [comment]
Thanks for raising the issue. This seems to be a simple fix to just replace the `action_space` with `single_action_space`. @dosssman would you mind taking a look at this? Does this impact our benchmark results?

**Comment by vwxyzjn** [comment]
Wait, I just tested the code and it works just fine.

```

**Comment by dosssman** [comment]
Also working as expected on my side.
Maybe a dependency problem ? Or an older branch ?

**Comment by vwxyzjn** [comment]
Yeah I added a checklist item in the issue item saying please make sure to install dependencies correctly via `poetry install`. See #180
