### ISSUE TITLE
[Request] Dexterous Manipulation Benchmark

### ISSUE THREAD

**Issue by kevinzakka** [vwxyzjn/cleanrl#185]
Hey Costa,

Been working on some dexterous manipulation tasks and looking for feedback on how to improve the physics parameters / reward values. Was curious if you'd be down to run some experiments together :) 

Here's a link to the repo: https://github.com/kevinzakka/dexterity

**Comment by vwxyzjn** [comment]
Hi @kevinzakka,

Thanks for reaching out! This looks really cool. Does dexterity have a gym API by any chance? I'd be happy to help.

**Comment by kevinzakka** [comment]
@vwxyzjn Unfortunately not, I'm trying to stay away from that API as it seems the devs like to keep making breaking changes :| I've used a dmc2gym wrapper for testing and it works fine though :)

**Comment by kevinzakka** [comment]
In terms of making this as accessible as possible to the community, do you think I should provide a wrapper in the package itself or is pointing to an open-source converter OK?

**Comment by vwxyzjn** [comment]
That's understandable. I think maybe having a converter example would be helpful (either you implement it or use dmc2gym)

I am trying some open source wrapper here but they don't seem to work so well... 

https://gist.github.com/vwxyzjn/18e1685945f3724a605fcf0d5730bfa5

**Comment by kevinzakka** [comment]
I'll take a look this weekend, thanks @vwxyzjn !!

**Comment by vwxyzjn** [comment]
Hey just following up with this: anything I can help?

**Comment by kevinzakka** [comment]
Hey @vwxyzjn, going to close this for now -- got something up and running without a dmc2gym conversion. Slightly busy in the next couple of weeks, so I'll keep you posted if/when I try to create the benchmark policies for the tasks. 

Cheers!

**Comment by vwxyzjn** [comment]
That sounds good! Your project looks really interesting and let me know if there is anything I can help.
