### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by vwxyzjn** [vwxyzjn/cleanrl#202]
## Problem Description
While CleanRL is standalone and licensed under MIT, it does depend on more copyleft dependencies like GPL. See #201 or https://app.fossa.com/reports/fdbf4b3e-435b-4db2-bc6b-57296284358f

<img width="523" alt="image" src="https://user-images.githubusercontent.com/5555347/173834708-d0f84067-726f-450d-95f1-3d9559a78b45.png">

Since we are not modifying these GPL codes so I think it's fine, but this is something to take note of.

**Comment by stefan-hdt** [comment]
Generally, if you do not change components under copyleft licenses (e.g. GPL-2.0) you do not have to provide the (changed) source code. But using your component "CleanRL" together with dependencies under copyleft licenses might make it necessary to license the combination under the copyleft license. This is especially the case for licenses with a strong copyleft clause.

**Comment by vwxyzjn** [comment]
Thank you for this thought - am I fine still licensing CleanRL itself under MIT?

**Comment by stefan-hdt** [comment]
Yes, you are fine licensing CleanRL unter MIT. This gives anyone who wants to use your software a lot of flexibility - if that is what you intend to achieve. 

As long as you look at the source code of your program the MIT license is the only license which applies. But when you link your code to a component under GPL-2.0 and compile it, the result (object code) will be only under GPL-2.0.
