### ISSUE TITLE
PPO with Humanoid

### ISSUE THREAD

**Issue by AdityaGudimella** [vwxyzjn/cleanrl#215]
## Problem Description
PPO doesn't learn on Humanoid

## Checklist
- [x] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [x] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo (required)

## Current Behavior
PPO doesn't seem to learn on the Humanoid-v3 env. In 50m iterations, the maximum reward it reached was 1200.

## Expected Behavior
The maximum reward that SAC can reach on Humanoid-v3 is ~5000. The original PPO paper doesn't mention performance on Humanoid. Is this performance on Humanoid expected?

## Steps to Reproduce
1. Run the `ppo_continuous_action.py` script with env-id as "Humanoid-v3"

**Comment by vwxyzjn** [comment]
Thanks for raising this issue. Yes, this is expected. See our benchmark on openai/baselines. https://wandb.ai/openrlbenchmark/openrlbenchmark/reports/MuJoCo-openai-baselines--VmlldzoyMTgyNjM0

<img width="696" alt="image" src="https://user-images.githubusercontent.com/5555347/175449330-1d5feb6b-10d2-4721-a529-a8cfdcbc16c9.png">

It is possible to get much better performance with a different set of hyperparameters

```
poetry run python ppo_continuous_action.py --total-timesteps 10000000 --num-envs 64 --anneal-lr=True --clip-vloss=False --ent-coef=0 --learning-rate=0.00295 --max-grad-norm=3.5 --num-minibatches=4 --num-steps=64 --update-epochs=2 --vf-coef=1.3 --env-id Humanoid-v2
```

but it's gonna run much faster with envpool. See https://wandb.ai/openrlbenchmark/envpool-cleanrl/reports/MuJoCo-CleanRL-EnvPool-vs-openai-baselines--VmlldzoyMjA2NjI2

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/5555347/175449557-d7372adb-a03a-4145-84e4-48020bbb9fa1.png">


The source code is https://github.com/vwxyzjn/envpool-cleanrl/blob/main/ppo_continuous_action_envpool.py

Paper is at https://arxiv.org/pdf/2206.10558.pdf

**Comment by AdityaGudimella** [comment]
Thank you so much for the prompt response. I will close the issue then. And thank you for providing the other set of hyperparameters and the envpool suggestion. That is very useful.
