### ISSUE TITLE
Problems with PPO value loss

### ISSUE THREAD

**Issue by HamishDuncanson** [vwxyzjn/cleanrl#22]
https://github.com/vwxyzjn/cleanrl/blob/a1a902173cb0cd7e84e109fcfcfecbbb4b908882/cleanrl/ppo_continuous_action.py#L379

I believe this line is missing a .mean()

Also, are you meant to be multiplying the value loss by 0.5 in lines 377 and 379? Isn't that the purpose of args.vf_coef?

I notice there is a number of PPO implementations, and it looks like many of them have the same issue.

**Comment by vwxyzjn** [comment]
@HamishDuncanson Thanks a lot for examining the code and raise this issue. The latest commit should fix the problem.

The `0.5` is used in a similar fashion as it is used in `openai/baselines`: https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/ppo2/model.py#L68-L75

**Comment by vwxyzjn** [comment]
Closing the issue for now.
