### ISSUE TITLE
JAX + DQN

### ISSUE THREAD

**Issue by vwxyzjn** [vwxyzjn/cleanrl#220]
See #218. @yooceii and @kinalmehta have expressed interest in working on this. @kinalmehta is also interested in C51 (#221). 

@kinalmehta if working with DQN first helps with working on C51, feel free to also work on this issue (saying this because usually working with DQN helps with "warm-up"). That way we will have two DQN PR from both you and @yooceii, and we can review and reconcile the differences between the two PRs.

**Comment by kinalmehta** [comment]
DQN + JAX pull request is already merged. So closing this issue.
