### ISSUE TITLE
Possible mistake in normalization of returns

### ISSUE THREAD

**Issue by HamishDuncanson** [vwxyzjn/cleanrl#23]
https://github.com/vwxyzjn/cleanrl/blob/a1a902173cb0cd7e84e109fcfcfecbbb4b908882/cleanrl/ppo_continuous_action.py#L68

Shouldn't we subtract the mean: (rews- self.ret_rms.mean)

**Comment by vwxyzjn** [comment]
@HamishDuncanson this is done in the same way as `openai/baselines` https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/vec_env/vec_normalize.py#L32
