### ISSUE TITLE
PPO: Shouldn't advantages be recomputed after every minibatch update?  

### ISSUE THREAD

**Issue by georgepsh** [vwxyzjn/cleanrl#24]
https://github.com/openai/baselines/blob/master/baselines/ppo2/runner.py - here, lines 65-66
I was trying to reproduce the ppo paper results myself, and I noticed that in openai/baselines repo they compute GAE for each trajectory segment, but they don't use these advantages directly. They do some trick regarding the fact that **Adv = Return - Value**. Thus **Return = Adv + Value**. 
And then at https://github.com/openai/baselines/blob/master/baselines/ppo2/ppo2.py lines 165-166 they only pass returns to train method. 
And finally they compute advantages again regarding equation **Adv = Return - Value** here at line 136: https://github.com/openai/baselines/blob/master/baselines/ppo2/model.py

In your implementations you compute advantages only once, if I'm not mistaken. But to be honest, I'm not sure if it is actually crucial

**Comment by vwxyzjn** [comment]
They should be equivalent since value does not change.

**Comment by georgepsh** [comment]
> They should be equivalent since old value prediction does not change.

Hm, I guess you are right. For some reason I misinterpreted the code and thought they use new value after every update
