### ISSUE TITLE
AsyncVectorEnv

### ISSUE THREAD

**Issue by Jogima-cyber** [vwxyzjn/cleanrl#244]
Hello, I was wondering why not use AsyncVectorEnv instead of SyncVectorEnv ? I don't see any reasons trajectories should not be parallelized.

**Comment by vwxyzjn** [comment]
Good question! SyncVectorEnv is just easier to debug, but we can definitely use AsyncVecEnv.

**Comment by Jogima-cyber** [comment]
Thanks, just wanted to have your opinion on the subject. I will run some tests with it then.

**Comment by vwxyzjn** [comment]
FYI - if you want to add it, feel free to submit a PR incorporating a flag like this:

https://github.com/vwxyzjn/vectorized-value-methods/blob/65b4745198c77d9b252ac90f373d9ad019003d9f/ppo_continuous_action.py#L48-L49
