### ISSUE TITLE
Adding TRPO implementation

### ISSUE THREAD

**Issue by merak0514** [vwxyzjn/cleanrl#245]
TRPO is a famous and powerful tool in RL. Although it does not have many practical uses these days, it is very helpful for a learner to read a good implementation of TRPO.

**Comment by vwxyzjn** [comment]
Hi, @merak0514 thank you for raising this issue. Indeed it would be good to have TRPO as well. I personally won't have much time doing this but you and others are welcome to give it a try.

**Comment by HridayM25** [comment]
Hey!

Could I work on this if possible?

Thanks!

**Comment by vwxyzjn** [comment]
Sure. Please see our contribution guide.

**Comment by vwxyzjn** [comment]
Feel free to re-open the issue if you or someone else is interested.

**Comment by Jackory** [comment]
I can work on this.
