### ISSUE TITLE
RL Formulation

### ISSUE THREAD

**Issue by Hannibal046** [vwxyzjn/cleanrl#249]
Hi, I am a newbie for RL. And I am wondering if the following scenario can be framed as a RL problem ?
```
1. The environment provides agent multiple choices each of which has a reward
2. We need the agent to choose one
3. In the next state, there are another multiple choices for agent to choose.
```
Should this be framed as a RL problem ? Since the action space is not fixed. Do you have any insight ? Thanks so much !!

**Comment by vwxyzjn** [comment]
Hi this sort of general RL questions are not directly linked to CleanRL and should be discussed elsewhere like RL discord https://discord.gg/vjer7PZGc6.
