### ISSUE TITLE
TypeError: can't assign a list to a torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by Kimonili** [vwxyzjn/cleanrl#26]
I got the above error in the line 

https://github.com/vwxyzjn/cleanrl/blob/bb18a39f9f8a6d9890413aafc12cd10690c6182a/cleanrl/ppo.py#L217

as my state space is a list [Box(4,)]. In order to address it, I converted next_obs to a tensor before assigning it to the obs tensor's selected index. I am not sure if this is the optimal solution, but it worked.

**Comment by vwxyzjn** [comment]
I see. Try converting your observation to numpy array before feeding it to the `obs` array

**Comment by Kimonili** [comment]
I tried that as well, but got this `TypeError: can't assign a numpy.ndarray to a torch.cuda.FloatTensor`

It only worked when I converted the observation to a tensor.

**Comment by vwxyzjn** [comment]
What’s the exact output of `env.observation_space`?

**Comment by Kimonili** [comment]
`env.observation_space` output is `[Box(4,)]`

sample of `env.reset()` is this `[array([ 0.        ,  0.        ,  0.19867001, -0.69431174])]`

**Comment by vwxyzjn** [comment]
It's a little off. The correct formulation should not have the list to enclose the observation space.

```python
import gym

env = gym.make("CartPole-v0")

env.observation_space
Out[3]: Box(4,)

env.reset()
Out[4]: array([-0.03268225, -0.0439948 ,  0.04512396,  0.0162064 ])
```

**Comment by Kimonili** [comment]
Yes I know, the environment is a little tricky. It is the [multiagent particle environment](https://github.com/openai/multiagent-particle-envs) (the simple.py one). It is a multiagent one, that's why there is a list of observation spaces (one for each agent). 

So, when I do this `env.observation_space[0]` I get the classic `Box(4,)`.

**Comment by vwxyzjn** [comment]
I see. I am not very familiar with the multi-agent settings so unfortunately I could not give much help at the moment :(

**Comment by Kimonili** [comment]
Don't worry, the good thing is that it runs anyway!

Thank you for your time!
