### ISSUE TITLE
Refactoring on Class Arguments

### ISSUE THREAD

**Issue by vwxyzjn** [vwxyzjn/cleanrl#27]
## Problem Description

Since CleanRL has been using single-file implementations with no `main()` function, a lot of global variables are created, and sometimes we have code within a class access global variables when those global variables should be passed to the classes.

## Current Behavior

As an example, in https://github.com/vwxyzjn/cleanrl/blob/master/cleanrl/dqn_atari_visual.py,

```
class QNetwork(nn.Module):
    def __init__(self, frames=4):
        super(QNetwork, self).__init__()
        self.network = nn.Sequential(
            Scale(1/255),
            nn.Conv2d(frames, 32, 8, stride=4),
            nn.ReLU(),
            nn.Conv2d(32, 64, 4, stride=2),
            nn.ReLU(),
            nn.Conv2d(64, 64, 3, stride=1),
            nn.ReLU(),
            nn.Flatten(),
            nn.Linear(3136, 512),
            nn.ReLU(),
            Linear0(512, env.action_space.n)
        )

    def forward(self, x):
        x = torch.Tensor(x).to(device)
        return self.network(x)
```

The forward function uses the global variable `device`. This is slightly undesirable

## Expected Behavior

The forward function should be

```
    def forward(self, x, device):
        x = torch.Tensor(x).to(device)
        return self.network(x)
```

It would be great if someone is willing to take some time and refactor files. This problem is present in almost all of the files..

**Comment by adamcakg** [comment]
Hello @vwxyzjn , I'm looking for first issue... Is this issue still available? If yes can you mark me to it?

**Comment by vwxyzjn** [comment]
Yes @adamcakg, it is still avaialble. Thanks so much for contributing! If you need any help or want to chat, feel free to find me on slack!

**Comment by vwxyzjn** [comment]
@adamcakg This is an extraordinary effort! I have just merged the code. You must put a lot of effort and scrutiny in it. Thank you so much for helping format the code. I would love to hear what kind of RL projects you would want to do. Feel free to DM me on discord (Costa#2021) if you'd like to chat. I am also very open to collaborations.
