### ISSUE TITLE
Requirments - requirements-pettingzoo.txt

### ISSUE THREAD

**Issue by Matkicail** [vwxyzjn/cleanrl#283]
## Problem Description
Requirements are not including which version of Supersuit is being used.

## Checklist
- Tried to install with poetry however does not seem to be working on my end.
- [ X] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo (required)

## Possible Solution
Updating requirements.txt with the version of Supersuit used

**Comment by Matkicail** [comment]
I went through the poetry files in a past commit. I found that it works with supersuit 3.3.5.
However, I tried to use the same version of pettingzoo as in that poetry file and the requirements. I found that it did not work - not sure if just on my end.  It did work when I changed it to use pettingzoo 1.18.1

**Comment by vwxyzjn** [comment]
Please try the latest set of `requirementx.txt`. I tested the following commands and they worked.

```
pip install -r requirements/requirements-pettingzoo.txt 
pip install -r requirements/requirements-atari.txt 
AutoROM --accept-license
python cleanrl/ppo_pettingzoo_ma_atari.py
```

**Comment by vwxyzjn** [comment]
Closing now but feel free to re-open should you encounter additional issues.
