### ISSUE TITLE
GitPod instance errors out when running poetry install

### ISSUE THREAD

**Issue by LooseTerrifyingSpaceMonkey** [vwxyzjn/cleanrl#325]
## Problem Description
GitPod instance errors out when running poetry install

## Checklist
- [] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [X] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [X] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

## Current Behavior
After starting the GitPod instance from the README.md file, I attempt to run **poetry install**.  I receive the following: 

**RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)**

## Expected Behavior
Poetry installs the requirements without an error message. 

## Possible Solution
Ensure the correct version of poetry is specified/installed out of the box in the GitPod environment. 

A workaround: 
pip3 uninstall poetry
pip3 install poetry -U

## Steps to Reproduce
1. Click on the GitPod button on REAME.md.
2. Click through the steps to start the environment. Now, you wait for the environment to start. 
3. Log into a terminal. 
4. Ensure you are in the cleanrl directory. If not, cd to it. 
5. Enter **poetry install** in the terminal. 
6. Error message received.

**Comment by vwxyzjn** [comment]
It’s probably cached incorrectly. Would you mind creating a PR that updates the Dockerfile.gitpod and modify the poetry installation line to pip install poetry --upgrade?

**Comment by LooseTerrifyingSpaceMonkey** [comment]
Created a PR: https://github.com/vwxyzjn/cleanrl/pull/326

**Comment by vwxyzjn** [comment]
Closed by #326
