### ISSUE TITLE
Cleanrl for MARL

### ISSUE THREAD

**Issue by vbaddam** [vwxyzjn/cleanrl#330]
## Contribution to MARL

I would like to contribute to Cleanrl repo by extending RL algorithms to Multi-Agent Systems (i.e MARL). I have discussed the same with @vwxyzjn, and he suggested starting an issue here. If anyone is interested in contributing to MARL, please respond here. Going forward, we can lay out the roadmap and share the responsibilities. 

Thank you.

**Comment by vwxyzjn** [comment]
Thanks, @vbaddam, MARL it's an exciting research field that we would love to get into. May I ask which algorithm are you thinking of contributing?

Two related papers/projects recently caught my attention https://arxiv.org/abs/2209.10485 and https://github.com/oxwhirl/smacv2.

**Comment by vwxyzjn** [comment]
Oh cool. What is the simulation environment for MADDPG? Is it MuJoCo?

**Comment by vbaddam** [comment]
I will start with MultiAgent MuJoCo (https://github.com/schroederdewitt/multiagent_mujoco) since it could help us see the direct difference between Single Agent and Multi-Agent

**Comment by 51616** [comment]
@vbaddam @vwxyzjn I can give a hand for implementing MARL algos. I have a working MAPPO + MAMujoco implemented in torch. I think the big difference from single-agent code is the design about parameter sharing and agent and data handling. Please let me know if we should discuss this elsewhere.

**Comment by vbaddam** [comment]
Yes, Sure. @51616. It would be great to you have on board. Should we set up a meeting and discuss the structure so we can be on the same page?  

@vwxyzjn I think using JAX is a good suggestion. However, I'm still catching up with JAX. Maybe I can implement it using PyTorch and extend it for the next iterations.

**Comment by 51616** [comment]
@vbaddam Sounds great to me! Please hit me up after the holiday.

**Comment by rodrigodelazcano** [comment]
Hello everyone! I just wanted to jump into the conversation. @Kallinteris-Andreas  has done an amazing work refactoring the MultiAgent MuJoCo environments into the [Gymnasium-Robotics](https://github.com/Farama-Foundation/Gymnasium-Robotics) repo. They are using the Pettingzoo API and the documentation can be found here https://robotics.farama.org/envs/MaMuJoCo/ma_half_cheetah/. 

We are actively maintaining this repo and it would be great seeing benchmarks of these environments with new CleanRL MARL algos. 

Also, we are waiting to benchmark these environments before making a new release, so for the time being they have to be installed from source.

**Comment by kinalmehta** [comment]
Hello everyone! I have been working on MARL with JAX and PyTorch and can be of help. Let me know what you guys have planned out.

**Comment by 51616** [comment]
@vbaddam Could you make a roadmap + progress tracker for this?

**Comment by vbaddam** [comment]
Here is the checklist and progress [tracker](https://docs.google.com/spreadsheets/d/12ZwJYyTlI2m-uyuZTNjbJ55FuP9ecQAG51yqa6cIevY/edit#gid=1060859634).

**Comment by ffelten** [comment]
Hi,
I'm also interested to see this being implemented! I have recently been trying to adapt SAC from cleanRL to multi agent setting: [https://github.com/ffelten/MASAC](https://github.com/ffelten/MASAC). 

It is still a WIP but it seems to learn stuff from early results. I would love to hear feedbacks and or tips for such adaptation of algorithms.

Cheers,

**Comment by Halmoni100** [comment]
Hello!  I am working on a MARL project with a couple of other people, and so I'd be interested in roadmap/progress.

**Comment by vwxyzjn** [comment]
Looks like https://github.com/kinalmehta/marl-jax came up. Closing this for now
