### ISSUE TITLE
Add Polyak update to DQN

### ISSUE THREAD

**Issue by manjavacas** [vwxyzjn/cleanrl#346]
## Checklist
- [ ] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [x] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [x] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

## Current Behavior

Currently, [DQN implementation](https://github.com/vwxyzjn/cleanrl/blob/master/cleanrl/dqn.py) do a _hard_ update of the target network. However, it is possible to perform _soft_ updates by using a soft update coefficient, between 0 and 1 (Polyak update).

## Expected Behavior

Soft updates can increase the stability of learning, as detailed in the [original DDPG paper](https://arxiv.org/pdf/1509.02971.pdf). This is because the target values are constrained to change slowly. 

Although this idea came after the original implementation of DQN, it is equally applicable to this algorithm.

Finally, this is a solution implemented in other reference libraries such as [StableBaselines3](https://stable-baselines3.readthedocs.io/en/master/modules/dqn.html), although I would understand that it is not intended to be added for simplicity and adherence to the original DQN implementation.

## Possible Solution

In the current [DQN implementation](https://github.com/vwxyzjn/cleanrl/blob/master/cleanrl/dqn.py), substitute:
```
    # update the target network
    if global_step % args.target_network_frequency == 0:
        target_network.load_state_dict(q_network.state_dict())
```
by:
```
    # update the target network
    if global_step % args.target_network_frequency == 0:
        for target_network_param, q_network_param in zip(target_network.parameters(), q_network.parameters()):
            target_network_param.data.copy_(
                polyak_coeff * q_network_param.data + (1. - polyak_coeff) * target_network_param.data)
```

**Comment by vwxyzjn** [comment]
Hi thanks for raising this issue. This sounds like a good idea, especially since we are already doing polyak updates in https://github.com/vwxyzjn/cleanrl/blob/3f5535cab409a34e9f071c10b96a234925d8a8d5/cleanrl/dqn_jax.py#L231 (optax [docs on `optax.incremental_update`](https://optax.readthedocs.io/en/latest/api.html?highlight=incremental_update#incremental-update)).

Feel free to make a PR.
