### ISSUE TITLE
Both dqn_atari and dqn_atari_visual use different ReplayBuffers compared to other implementations

### ISSUE THREAD

**Issue by bentrevett** [vwxyzjn/cleanrl#35]
Thanks for creating this repo - I always have difficulty understanding RL algorithms when they're spread across huge libraries.

One question, both the `dqn_atari.py` and `dqn_atari_visual.py` both use the following `ReplayBuffer` class:
```python
# modified from https://github.com/openai/baselines/blob/master/baselines/deepq/replay_buffer.py
class ReplayBuffer(object):
    def __init__(self, size):
        self._storage = []
        self._maxsize = size
        self._next_idx = 0

    def put(self, data):
        if self._next_idx >= len(self._storage):
            self._storage.append(data)
        else:
            self._storage[self._next_idx] = data
        self._next_idx = (self._next_idx + 1) % self._maxsize

    def sample(self, batch_size):
        idxes = np.random.choice(len(self._storage), batch_size, replace=True)
        obses_t, actions, rewards, obses_tp1, dones = [], [], [], [], []
        for i in idxes:
            data = self._storage[i]
            obs_t, action, reward, obs_tp1, done = data
            obses_t.append(np.array(obs_t, copy=False))
            actions.append(np.array(action, copy=False))
            rewards.append(reward)
            obses_tp1.append(np.array(obs_tp1, copy=False))
            dones.append(done)
        return np.array(obses_t), np.array(actions), np.array(rewards), np.array(obses_tp1), np.array(dones)
```

However, `dqn.py`, `c51.py`, `c51_atari.py`, `cs51_atari_visual.py`, `sac_continuous_action.py`, and `td3_continuous_action.py` all use the following `ReplayBuffer`:

```python
# modified from https://github.com/seungeunrho/minimalRL/blob/master/dqn.py#
class ReplayBuffer():
    def __init__(self, buffer_limit):
        self.buffer = collections.deque(maxlen=buffer_limit)
    
    def put(self, transition):
        self.buffer.append(transition)
    
    def sample(self, n):
        mini_batch = random.sample(self.buffer, n)
        s_lst, a_lst, r_lst, s_prime_lst, done_mask_lst = [], [], [], [], []
        
        for transition in mini_batch:
            s, a, r, s_prime, done_mask = transition
            s_lst.append(s)
            a_lst.append(a)
            r_lst.append(r)
            s_prime_lst.append(s_prime)
            done_mask_lst.append(done_mask)

        return np.array(s_lst), np.array(a_lst), \
               np.array(r_lst), np.array(s_prime_lst), \
               np.array(done_mask_lst)
```

As far as I am aware, they look identical - but wanted to know if there was some implementation reason for why they are different?

**Comment by vwxyzjn** [comment]
Hi @bentrevett thanks for the report. I am glad you are enjoying our single-file implementations. 

Regarding the replay buffer issue, I was experimenting with both to see if there is a memory usage difference, but that does not seem to be the case. If it is convenient with you, feel free to make a PR changing the replay buffer class in `dqn_atari.py` and `dqn_atari_visual.py` to the one in other files.

**Comment by vwxyzjn** [comment]
Looks great! Thanks for the PR!

**Comment by vwxyzjn** [comment]
If you have a wandb user name, feel free to throw it at me and I will add you to the list of authors of https://benchmark.cleanrl.dev

**Comment by bentrevett** [comment]
Sure - it's the same as my github username: https://wandb.ai/bentrevett

**Comment by vwxyzjn** [comment]
Done! Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
