### ISSUE TITLE
About PPO+Procgen code on Jax

### ISSUE THREAD

**Issue by sglucas** [vwxyzjn/cleanrl#352]
Thank you very much for your contribution.

May I ask if is it possible to release the PPO+Procgen code based on Jax?

Best

**Comment by vwxyzjn** [comment]
Sure, we have upcoming plans for it #340. For now, you can use the source code [here](https://wandb.ai/costa-huang/cleanRL/runs/3659zaws/code?workspace=user-costa-huang), which at first glance is compatible with the performance of `ppo_procgen.py` (see [report](https://wandb.ai/costa-huang/cleanRL/reports/EnvPool-s-procgen-vs-procgen--VmlldzozMjU4MjIy)).

Let me know if you would be interested in helping with running benchmark experiments.

**Comment by sglucas** [comment]
Hi, Thanks for your reply!

Sure. May I ask this [code](https://wandb.ai/costa-huang/cleanRL/runs/3659zaws/code?workspace=user-costa-huang) is right?  Since I find the environment of this [code](https://wandb.ai/costa-huang/cleanRL/runs/3659zaws/code?workspace=user-costa-huang) is atari (breakout).

Best

**Comment by vwxyzjn** [comment]
The code link is correct. If you look at the summary of the tracked experiment, the `env_id` is `BigFishEasy-v0`, which is one of the procgen’s environments. As pointed out in #340, EnvPool >=0.8.1 introduces procgen environments, basically allowing us to handle Atari and procgen using the same codebase. There are minor API differences, though, if you try to diff the code and what was used to handle Atari at #338 (mostly minor API differences). Also note that there are differences in hyperparameters.

A good way is to probably rename #338's implementation as `ppo_impalacnn_jax_scan.py` which handles both Atari and procgen environment. Could you give it try and make a PR based on #338? Happy to provide more context and info.

**Comment by sglucas** [comment]
Hi @vwxyzjn do you try to use this link https://github.com/bmazoure/ppo_jax. I find the current code does not test the learned policy in all 1000 environments.

**Comment by vwxyzjn** [comment]
Related https://github.com/bmazoure/ppo_jax/issues/2

**Comment by sglucas** [comment]
Hi, I'm still a little confused by the results on bigfish. Since I find the result in this repo is much higher that the results that some published papers claimed. I'm not sure whether my understanding is right. such as Table 6 and Table 7 in https://arxiv.org/pdf/2006.12862.pdf, and https://arxiv.org/pdf/1912.01588.pdf.

**Comment by vwxyzjn** [comment]
https://github.com/vwxyzjn/cleanba should work with procgen if you want to take a look :)
