### ISSUE TITLE
The file 'ppo_memory_env_lstm.py' can't be found

### ISSUE THREAD

**Issue by leeivan1007** [vwxyzjn/cleanrl#356]
## Problem Description
The file 'ppo_memory_env_lstm.py' can't be found

## Checklist
- [ x ] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [ x ] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [ x ] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

## Current Behavior
I saw the README file it showed a paragraph can run 
```
python cleanrl/ppo_memory_env_lstm.py
```
But it can't be found in whole repository

## Expected Behavior
It can train and run the ppo_memory_env_lstm

## Possible Solution
No ideas

## Steps to Reproduce
1.python cleanrl/ppo_memory_env_lstm.py

## Others

Btw I found the other file in here [ppo_memory_env_lstm](https://programtalk.com/vs4/python/vwxyzjn/cleanrl/cleanrl/ppo_memory_env_lstm.py/)

Thanks!

I can help if there is something need to help

**Comment by vwxyzjn** [comment]
Hey `ppo_memory_env_lstm.py` was left there unintentionally. However feel free to test https://programtalk.com/vs4/python/vwxyzjn/cleanrl/cleanrl/ppo_memory_env_lstm.py out to play with it

**Comment by leeivan1007** [comment]
Got it. Thank you for your response!
