### ISSUE TITLE
Is SAC exploration-noise used?

### ISSUE THREAD

**Issue by StoneT2000** [vwxyzjn/cleanrl#361]
Was looking at the SAC continuous action implementation and I noticed theres an used exploration-noise parameter. Is this used anywhere (or by any other libs?)

https://github.com/vwxyzjn/cleanrl/blob/master/cleanrl/sac_continuous_action.py#L52

Currently trying to compare my own code with OpenRL Benchmark results so was trying to align the hyperparameters.

**Comment by vwxyzjn** [comment]
Ah this is probably just copied and pasted from the ddpg base implementation. Let me make a PR to remove it.
