### ISSUE TITLE
Poetry install fails: WheelFileValidationError: Pytorch 1.12

### ISSUE THREAD

**Issue by samholt** [vwxyzjn/cleanrl#365]
## Checklist
- [x] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [x] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [x] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

## Current Behavior

When running `poetry install`. The installation fails, with the following.

```
_WheelFileValidationError

["In /root/.cache/pypoetry/artifacts/21/ea/bc/a9bb54ed951969eeae8a2bec49ad9c6a1b2a4c204d2aad9f2fb71d2eec/torch-1.12.1-cp38-cp38-manylinux1_x86_64.whl, hash / size of torch-1.12.1.dist-info/METADATA didn't match RECORD"]
```

This occurs both running the install process on Ubuntu and inside the Docker image build.

## Expected Behavior

I expect when running `poetry install` to complete successfully.

## Possible Solution

I expect this occurs due to a version change of PyTorch? If so what would be a suitable version that should work?

## Steps to Reproduce

1. `git clone https://github.com/vwxyzjn/cleanrl && cd cleanrl`
2. `poetry install`

**Comment by vwxyzjn** [comment]
Thanks so much for reporting this. This feels like a fairly recent poetry issue https://github.com/python-poetry/poetry/issues/7691. Consider using poetry@1.3.1. Please let me know if that resolves the issue :)

**Comment by samholt** [comment]
Using poetry@1.3.1 resolves the issue! Thank you so much.
