### ISSUE TITLE
Poetry installation failure on master

### ISSUE THREAD

**Issue by smorad** [vwxyzjn/cleanrl#391]
## Checklist
- [ ] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [x] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [x] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

## Current Behavior
```python
...
  • Installing moviepy (1.0.3): Failed

  ImportError

  cannot import name 'Python2Supports' from 'virtualenv.create.describe' (/Users/smorad/miniforge3/envs/cleanrl-poetry/lib/python3.10/site-packages/virtualenv/create/describe.py)

  at ~/miniforge3/envs/cleanrl-poetry/lib/python3.10/site-packages/virtualenv/create/via_global_ref/builtin/python2/python2.py:6 in <module>
        2│ import json
        3│ import os
        4│ from pathlib import Path
        5│ 
    →   6│ from virtualenv.create.describe import Python2Supports
        7│ from virtualenv.create.via_global_ref.builtin.ref import PathRefToDest
        8│ from virtualenv.info import IS_ZIPAPP
        9│ from virtualenv.util.zipapp import read as read_from_zipapp
```

## Expected Behavior
Cleanrl should install without crashing.

## Steps to Reproduce
On MacOS ARM64:
```bash
conda create -n cleanrl-poetry python=3.10 poetry
conda activate cleanrl-poetry
poetry install
```

**Comment by vwxyzjn** [comment]
i wonder if I this is a arm64 issue. Can you try with Rosetta?

**Comment by vwxyzjn** [comment]
This is using rosetta. I used pyenv to manage virtual envs. I did not use conda.
