### ISSUE TITLE
run and experiment_name from docs/advanced/resume-training are undefined

### ISSUE THREAD

**Issue by Melanol** [vwxyzjn/cleanrl#399]
## Problem Description
[Here](https://docs.cleanrl.dev/advanced/resume-training/#resume-training_1). Also, am I supposed to use cleanrl_utils/resume.py instead of what is in the docs?

## Checklist
- [x] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [x] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [x] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

**Comment by vwxyzjn** [comment]
The `resume.py` is something slightly more advanced (and kind of deprecated). You should rely on the pointers in docs.

**Comment by Melanol** [comment]
@vwxyzjn Docs are not helpful, as `run` and `experiment_name` are not defined anywhere before the following part, including algos:
```python
if args.track and wandb.run.resumed:
    starting_update = run.summary.get("charts/update") + 1
    global_step = starting_update * args.batch_size
    api = wandb.Api()
    run = api.run(f"{run.entity}/{run.project}/{run.id}")
    model = run.file("agent.pt")
    model.download(f"models/{experiment_name}/")
    agent.load_state_dict(torch.load(
        f"models/{experiment_name}/agent.pt", map_location=device))
    agent.eval()
    print(f"resumed at update {starting_update}")
```

**Comment by vwxyzjn** [comment]
`experiment_name` is now `run_name`. 

    api = wandb.Api()
    run = api.run(f"{run.entity}/{run.project}/{run.id}")

**Comment by Melanol** [comment]
> run = api.run(f"{run.entity}/{run.project}/{run.id}")

You are trying to define `run` with `run` that is not defined.

**Comment by vwxyzjn** [comment]
Oh i see. The run is 
![IMG_5655](https://github.com/vwxyzjn/cleanrl/assets/5555347/37761c3d-f804-4bc3-8aef-4a0c3cb5c165)


Here is the reference code https://wandb.ai/costa-huang/cleanRL/runs/21421tda/code?workspace=user-costa-huang
