### ISSUE TITLE
Is action masking supported in PPO?

### ISSUE THREAD

**Issue by aqibsaeed** [vwxyzjn/cleanrl#402]
Hi, Thanks for the great work. Could you please let me know, if the current PPO implementation has action masking?

**Comment by vwxyzjn** [comment]
Kind of. Please use https://github.com/vwxyzjn/ppo-implementation-details/blob/main/ppo_multidiscrete_mask.py 

I did not include it in CleanRL because I did not want to include the gym-microrts dependency.

**Comment by aqibsaeed** [comment]
Thanks alot!
