### ISSUE TITLE
AWS example?

### ISSUE THREAD

**Issue by drozzy** [vwxyzjn/cleanrl#43]
Do you guys have an example of how to run this on AWS? I've never done it but it sounds intriguing.
Also, what kind of costs do you pay for training a single game, for example?

**Comment by vwxyzjn** [comment]
Hi, that is a good question. We don't have formal documentation on the integration with AWS, but you might find this useful:

https://costa.sh/blog-how-we-conduct-large-scale-drl-experiments.html

Unfortunately, the blog post is a bit dated. How soon do you need the documentation? The commands I use to submit experiments for https://github.com/vwxyzjn/gym-microrts-paper look more like:

```
pip install cleanrl
mkdir scripts
python -m cleanrl.utils.submit_exp --exp-script scripts/ppo_gridnet_coacai_naive.sh \
    --algo paper/ppo_gridnet_coacai_naive.py \
    --total-timesteps 300000000 \
    --gym-ids MicrortsDefeatCoacAIShaped-v3 \
    --wandb-project-name gym-microrts-paper \
    --other-args "--wandb-entity vwxyzjn --cuda True" \
    --job-queue cleanrl_gpu \
    --job-definition gym-microrts \
    --num-seed 4 \
    --num-vcpu 3 \
    --num-gpu 1 \
    --num-memory 13000 \
    --num-hours 720.0 \
    --submit-aws False

# if the experiment crash, 
python -m cleanrl.utils.resume \
    --wandb-project vwxyzjn/gym-microrts-paper \
    --run-state crashed \
    --job-queue cleanrl_gpu \
    --job-definition gym-microrts \
    --num-seed 4 \
    --num-vcpu 3 \
    --num-gpu 1 \
    --num-memory 13000 \
    --num-hours 720.0 \
    --submit-aws $SUBMIT_AWS
```

**Comment by drozzy** [comment]
All good, this was merely a curiosity.
