### ISSUE TITLE
expected sequence of length 8 at dim 1 (got 0)

### ISSUE THREAD

**Issue by flypark666** [vwxyzjn/cleanrl#431]
## Checklist
- [ ] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [ ] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [ ] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

## Current Behavior

next_obs = torch.Tensor(envs.reset()).to(device)
ValueError: expected sequence of length 8 at dim 1 (got 0)
## Steps to Reproduce

1.
2.
3.
4.

**Comment by flypark666** [comment]
no,I just use pip install

> Did you do poetry install? It sounds like a dependency issue

**Comment by vwxyzjn** [comment]
Please follow the installation instructions https://docs.cleanrl.dev/get-started/installation/#prerequisites

**Comment by flypark666** [comment]
I try to poetry install,but some other problems happen,
<img width="564" alt="image" src="https://github.com/vwxyzjn/cleanrl/assets/52408602/4b3982f2-0848-4351-a16e-4f7f87dea724">
<img width="839" alt="image" src="https://github.com/vwxyzjn/cleanrl/assets/52408602/9f9427ec-5b4c-49f2-a360-78fba175e9c8">
