### ISSUE TITLE
can't upload video running ppo_atari.py,wandb has no data

### ISSUE THREAD

**Issue by flypark666** [vwxyzjn/cleanrl#436]
## Problem Description

<img width="929" alt="image" src="https://github.com/vwxyzjn/cleanrl/assets/52408602/c472838f-4adf-4393-b38c-983e261a3dec">

    track: bool = True
    wandb_project_name: str = "cleanRL"
    wandb_entity: str = None
    capture_video: bool = True

<img width="992" alt="image" src="https://github.com/vwxyzjn/cleanrl/assets/52408602/d5fc99a1-9fd8-4fa0-9bbf-4b71522e3de5">

## Checklist
- [yes ] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [ yes] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [ yes] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

## Current Behavior

can't upload and wandb has no data
## Steps to Reproduce

1.
2.
3.
4.

**Comment by vwxyzjn** [comment]
I believe you just need to add `env = gym.make(env_id, render_mode="rgb_array")` in line 92. Could you test it out #437?

<img width="791" alt="image" src="https://github.com/vwxyzjn/cleanrl/assets/5555347/acf4c1d8-ee3d-4788-869c-44b15aac5396">

**Comment by flypark666** [comment]
@vwxyzjn Thanks a lot, but my wandb still has no other date like episodic return, I don't konw why.
<img width="975" alt="image" src="https://github.com/vwxyzjn/cleanrl/assets/52408602/bb8b96e4-f5e1-4887-aec0-e5c1fe165d59">

**Comment by flypark666** [comment]
windows

**Comment by vwxyzjn** [comment]
Sorry could you try running the code in docker? I imagine this is a windows wandb issue…

**Comment by flypark666** [comment]
Ok, thank you, I will try.
