### ISSUE TITLE
Improve compatibility with CUDA-enabled pytorch on non-CUDA devices

### ISSUE THREAD

**Issue by mainrs** [vwxyzjn/cleanrl#461]
## Problem Description
The pytorch CUDA-enabled libraries are more capable than the CPU-only one. They can also run on the CPU if no CUDA device is available. However, due to a race condition, the current code base calls into the CUDA driver even if one passes `--no-cuda` as an argument. 

The issues are these lines of code: https://github.com/vwxyzjn/cleanrl/blob/8cbca61360ef98660f149e3d76762350ce613323/cleanrl/dqn.py#L147

They should first check if the flag is set and only then call `torch.cuda.is_available`. That way, the program runs perfectly fine in those scenarios.

## Possible Solution
```py
device = torch.device("cuda" if args.cuda and torch.cuda.is_available() else "cpu")
```

**Comment by pseudo-rnd-thoughts** [comment]
Could you clarify why this is a "race condition"?

it shouldn't be `cuda` unless both cases are true so I don't understand why ordering would matter in this case

**Comment by mainrs** [comment]
Because Python's `and` is lazy. If the first option is false, than it doesn't evaluate the second one. If I pass `--no-cuda`, Python still runs `torch.cuda.is_available`, even though I specified that I do not want to use CUDA. 

On devices that don't have CUDA drivers but have the CUDA version of PyTorch installed, this throws a runtime error. However, using the CPU on such devices is valid, since the PyTorch library can still function with CPU.

**Comment by pseudo-rnd-thoughts** [comment]
Ok, that makes sense, I thought that pytorch would be smart enough to not raise a runtime error for this function. 
I would make a PR that makes your suggested change

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
