### ISSUE TITLE
JAX has no gpu version

### ISSUE THREAD

**Issue by ItsBean** [vwxyzjn/cleanrl#482]
## Checklist
- [ ] I have installed dependencies via `poetry install` (see [CleanRL's installation guideline](https://docs.cleanrl.dev/get-started/installation/).
- [ yes] I have checked that there is no similar [issue](https://github.com/vwxyzjn/cleanrl/issues) in the repo.
- [ yes] I have checked the [documentation site](https://docs.cleanrl.dev/) and found not relevant information in [GitHub issues](https://github.com/vwxyzjn/cleanrl/issues).

## Reviewer xxxx

In the `requirements-jax.txt` file, the JAX package information is listed as follows:
```
jax-jumpy==1.0.0 ; python_version >= "3.8" and python_version < "3.11"
jax==0.4.8 ; python_version >= "3.8" and python_version < "3.11"
jaxlib==0.4.7 ; python_version >= "3.8" and python_version < "3.11"
```

This configuration is for CPU users of JAX. Could the authors please provide a GPU version of the `td3_jax` code along with a `requirements-jax-gpu.txt` file? Your contribution would be greatly appreciated.

Additionally, I am unable to directly upgrade JAX to the GPU version because the `td3_jax` code relies heavily on `Flax` and `Optax`. Any guidance or support on this matter would be extremely helpful.

**Comment by kinalmehta** [comment]
You may refer [jax documentation](https://jax.readthedocs.io/en/latest/installation.html) to install GPU version
