### ISSUE TITLE
Broken links on README

### ISSUE THREAD

**Issue by FelipeMartins96** [vwxyzjn/cleanrl#53]
## Problem Description
Broken links on Algorithms Implemented section of README 

## Current Behavior
Links are pointing to unavailable pages

## Expected Behavior
Link should point to desired code

## Possible Solution
Remove links to removed code or change links to new location

## Steps to Reproduce
The link to the following codes on README implemented algorithms section are pointing to old locations, resulting in page 404:

experiments/ppo_self_play.py
experiments/ppo_microrts.py
experiments/ppo_simple.py
experiments/ppo_simple_continuous_action.py

not sure if there are more links, i found these one as they are on the experiments folder which does not exist anymore

**Comment by vwxyzjn** [comment]
Hey @FelipeMartins96  thanks for reporting the problem. Yeah those links are broken due to some cleaning up. Would you mind making a PR removing the references to these links?

**Comment by FelipeMartins96** [comment]
sure! Will do that
