### ISSUE TITLE
Documentation Site

### ISSUE THREAD

**Issue by vwxyzjn** [vwxyzjn/cleanrl#57]
## Problem Description
Although CleanRL generally has a simplistic implementation, it will be desirable to have a documentation site for some situations. For example, I'm not sure where to put instructions on how to do start and resume with CleanRL's scripts. See #33, #14.

**Comment by dosssman** [comment]
Are the start and resume independent of WANDB and AWS ?

**Comment by dosssman** [comment]
> > Are the start and resume independent of WANDB and AWS ?
> 
> it’s dependent on wandb because we need to store the timestep somehow.

In such case, I would say the relevant instructions could go to the wandb / cloud integration documentation section.

**Comment by vwxyzjn** [comment]
I am a little in favor of mkdocs, becuase in https://fastapi.tiangolo.com/tutorial/ you can see like an animated terminal and that in the other pages you can highlight code

**Comment by vwxyzjn** [comment]
Closing this issue now. Docs site is already live at https://docs.cleanrl.dev
