### ISSUE TITLE
Proper entropy regularized PPO

### ISSUE THREAD

**Issue by 51616** [vwxyzjn/cleanrl#73]
## Problem Description
Seems like the current implementation of PPO use only one-step entropy bonus (not including the entropy bonus in the overall return). I see this as a ease of implementation that passed along from other popular repos. Do you consider implementing the proper entropy regularization in this repo? It seems like the performance gain might me crucial in some cases as shown in this [paper](https://arxiv.org/pdf/1704.06440.pdf) (section 6.1). The main difference is shown in eq.79-80 in section 6.1

## Current Behavior
Using one-step entropy bonus

## Expected Behavior
Using proper entropy bonus

## Possible Solution
The entropy bonus should be added to the rewards before computing the advantage. This should be simple to implement as it changes `r` to `r + entropy` then the rest of the process should be the same if I am not mistaken.

**Comment by 51616** [comment]
@vwxyzjn I have tested the proper version. The results look very good on Pybullet's HalfCheetah (hovering around 2200 after 1M steps which is higher than the current version of PPO) And the score on Breakout looks similar to the normal version.

**Comment by vwxyzjn** [comment]
@51616 Thanks for reporting back. This is great to know. Have you tracked the experiments by any chance? I'd love to see the learning curves and stuff. If you have the URL to the experiments that will be great.

**Comment by 51616** [comment]
@vwxyzjn I did not turn wandb tracking on. I'll do that tonight and send you the report link right after. And the PR should be simple enough. Should we try comparing runs from naive and proper version across many tasks? 'Cause this change would make the implementation in this repo differs from others. So it might have to be justified and we should be confident that the change really matters.

**Comment by vwxyzjn** [comment]
@51616 that’s a good point. I’d be careful with committing this change directly to the files. Maybe you can create a folder called `ppo_wth_proper_enropy_tuning` and create the three ppo files in there? If you create a PR I could also help some experiments.

**Comment by 51616** [comment]
@vwxyzjn Sorry for a late reply. It seems like the improvement I reported is just a noise :( It seems like the continuous control tasks do not benefit from using entropy regularized objective in the first place. And I see no clear improvement for Atari tasks as well. Do you still want to try it out? I can make a pull request of my implementation

**Comment by 51616** [comment]
And the tracked stats is here: https://wandb.ai/51616/proper_ppo_entropy?workspace=user-51616

**Comment by vwxyzjn** [comment]
Hey thanks for running these tests. So I think the best way to proceed from this is to make a PR and put everything under a folder like `ppo_wth_proper_enropy_tuning`, and also include a README.md that explains this proper entropy regularization and have a pointer to the tracked stats.
