### ISSUE TITLE
This is a great job. I want to ask, how should you plot the following curves? seaborn or wandb? If use wandb, how to edit this? Thanks

### ISSUE THREAD

**Issue by caimingxue** [vwxyzjn/cleanrl#96]
![question](https://user-images.githubusercontent.com/45029643/145507809-e83d0bad-81a8-48e7-a8a6-8e8345a612a6.png)

**Comment by vwxyzjn** [comment]
Hey, checkout https://github.com/vwxyzjn/cleanrl/pull/55. You could also export that curve directly from the wandb dashboard (although less configurable).
